jdk: openjdk8

jobs:
  include:
    - stage: build
      before_install: ./install-protoc.sh
      script: ./build.sh
      deploy:
        provider: script
        script: deployment/deploy-release.sh
        skip_cleanup: true
        on:
          tags: true
          repo: cloudstateio/springboot-support

    - stage: validate_docs
      script: make -C docs

    - stage: deploy_docs
      if: repo = cloudstateio/springboot-support AND tag =~ ^v
      script: make -C docs deploy

stages:
  - build
  - validate_docs
  - deploy_docs

env:
  global:
  # Bintray username encrypted with: travis encrypt --pro -r cloudstateio/springboot-support BINTRAY_USERNAME={username}
  - secure: "fk7KI476nos7Yrt5yE6KKqTG7qJe8KgnNTiECVXuhcw/5S5IT9Hs3aMB0rI/fTZAyhX08pviZLaRcxSoB1VPDCNJxIqhjJkDdKEisCF0jWDxNx5Zg3v5hffMudrjCto6CgpGbI1aet7d5N+8IXTFKy3s5vyZnMMwKywXg6OFc7r3yUsTEAopY8dCaY6nyfMphyAgbwS+LXbX+DFoUqtt824uvhN6iBGrlE0MtJnwle3acnGqQkavYy6D0nkaIYlnD3SA84i90vB0qPadORgd6BLX3PWcp/ZgGF4w1uk0fq6p5G4/o32q55BF3sG4xDVcM2mYCI39wz1PpT3Xc94GjoUnFX1qrCbX6cBbiSuB85K2G+ZuYgngBWgIJl4LEGVpIPR6JONc1/0mzROyaU5lF/xzMO2QLdSiQ+fMHaN3wbuxoKddLgHmJISBrd2BL3Wj2X7Es78IMZxVWLtCWpyBJYEv7lTsy+KMTbjz0mKI6wbYubYvWDyTv+IhMI+SqNsAbYtd8+UfJ/gRmTGJAxflwUzQ4FWaSkyr53sCjfDsgNR1YiytWNRYdchkN4ymI5khZAepcHpJikRi8e7NyjDzKkCP3/axgcNjcMbfLvDtkGGpVJaXFqykFjKyEWg8Qi9rzcGU7mU6/IFgjRHFPYZ1hTJe7cenP0Umcpda7NB2Ziw="
  # Bintray API key encrypted with: travis encrypt --pro -r cloudstateio/springboot-support BINTRAY_PASSWORD={password}
  - secure: "aYxwzNgvlh8hLpRUDu+p8RfhmjUCA3HoJ3iJgcaDoBdttsIS7vQbWIOALhbauoYjQvmNfbW3p9vpog/YlxEnEQQSN+UvA7QttAPFE24TCiqOAxD1JTBQ5k8L6ZmOJBhsl8l/zIejQ4XVLO8GfEhXrFziBxAzmnIumQmvuonAz6qmhvk/q2aWHzLuYml0vvHkRCL2n5Rf75S5/Wsnpgm9BcVoGj6d0+HyQY5T3GOHHykgExXQdXRkrdfG1IDWYmlXGif+TL/tZN7RMJLHBstFaPalQfvu25RoNGcTK3j+daYUDoSu00CMugd6AutlmSFKqTfDLUR5mPeKbh0x9s75tSjCjsgBwrD/uB405FYvYNZcJhXpvARENCBXGoPMxFbe237/doB6LZAN0kTmcoY1zx13aymcooAinq7hj0fBW6pP7O7AKGbY/AsQUw6BAgo7vbBPoXKi6d3KaEUjbFqNi8Z14Gocdy+xUG70vW/ot8oaryGmAgjooIjHQVf7vwxYSPnFJg9iHZMwF09HAxlmx83zLhLEMscrhbBIX0ZbEkYYc5OEit4mz/OTPnly9M8REarb4xvYxC+tRN1l4Zt0OnBvAnB8l05aIOX8QJ9mWv/2XgG5dycbDagApcWCYAOR9B84FywvhPvkXEFVE9n7RWfaeGWgtZYBdphTIfvf81g="
  # Sonatype user token key encrypted with: travis encrypt --pro -r cloudstateio/springboot-support SONATYPE_USERNAME={username}
  - secure: "XeuNWIS30BvCRORyDUAj3h2U5jximOQRFhd7b+AyCx+qNAjFE0FsTjvAOKnTyNzazOMjkEX9llDxGKwmxOS3g1P3W8pprDi9Y4hXc7XUGU1QiiDKaxQ9yxYVV9JUF18hVrw3oIxIWy6DJVsJ5EC5zrYh7gezi3UaywAC//fx+qfTmzM9E/sCXkh2sOnnxmd2gXksBjZ6ItSb98kQIRsgXwpNNWEAOdnsYJiCOxs/AnhEeuxISogT6GmCJ/IOtIN8sjBiLZmuA5nAIhNX0nIIJSl0WM58Ib6Uuj/A/5TRW9X0NUuMNFDMVyxRfOGucGW2ahm2QJy+Vmh3Gn3g4R5Mw1UVQQbaxjMkrStIEDq32OGnP3yJHKapSwUS0ICq4Fb+dT7PTn0a+DMbraKDo4+2HizM2IO9WgY3HJYis3Kz7Om1gRT8/1i3cavhO/zYq3K0mgKcFN5W/sZjySSidgpL+/rkGfroyvaHr7NTEHXQ3mWPofhPSEd8u3Z4lQySnNGkQY+gsqf3TBPGnlZ9hvrmPTIq9f8TrfMYRza6w6c8zZCQFwq+IR1c4qwr3HVG9B/3v5xQ/8PbpzmVoTtqwUD4YrK4XVLbONyLRbKF6Hi5pxgJu6OjeUUUyU+pD06b90BSOhuHi/wYFYVBXgNaHoujAVtYBblnZ+Lb3UMdRZimhVA="
  # Sonatype user token password encrypted with: travis encrypt --pro -r cloudstateio/springboot-support SONATYPE_PASSWORD={password}
  - secure: "ldjb5+o+lj4LjZwywoAuHahliAKO3Ne6A4RAQp+1zHfEOGldGJpBhQV+W2C5r60+8/mGFCmVRhxrxCI44OQb7rASc95uGMFRn6o8oS2XZJKsfH8EGT9y8tHb0LAgHkqGEP1y5LM3RYscIiBylDUuyNWzhPM/NrIocUq8QGZYW/YkE+TVzm+S9cTVhyYaLBebhZsP4wpYVAPfMiv79yBm90J+jWp8xiNWhGiGSS4JihQQO23hmlxxEDlh9SyPDvfrTwwgWvnQ1kuufNv2CRXjmZjE42O7ntx8AtvhQSMuPuqY9pq4RwSv6+wA2Jx1xNBmrqsqGCVUjGVPO8CyIWAPnE8ytIeAWFwsmXdRNCrzzeObTZ07WNPES7WTAhXdXnZw/Xzn74VMmdPT0H0gIQTmUqVwylwfiatqLjxHsOnsv7Up74BMawxsbIPbdubN+490SnPqIRRTPEV0Pv1ecCquUP6hOvvjPl6vkkH773+jCjiHpgpEFnkVvQyyEbAp8oTparqqgu3f1BoUxVXhA2OguOnsCwqsNVSMhDfcT+tgPDiftNq18UacRIWZ/Y38F+bXSQAU9okvDvaW1TwL6kG0MhHXtTF+OtTZe+unaA6VVD5xdZFV69I7YX4un4bnOXUUzLhwonVXNnPiGp3Iyv3wSGqivxaQkLROOde8gSqwO5Y="
  # Deploy docs token encrypted with: travis encrypt --pro -r cloudstateio/springboot-support DEPLOY_DOCS_TOKEN=<token>
  - secure: "APu+EMZd15Ef93pzm8CS0dHI5NXdCBNZ1S6A8FFN7zNgxG1FUEaxBqr4zrPdiRETY+HTB1aui1mXC8THBvMKHpv5FihQD7IshYQ8HPr8P9QVik2NYV2iPAnca1D7LZtlAWFB8HV8p9vTw9qnXmOYaAgLAdCBQDVUZc3brf6k7MB+YuOsSdNgPan6VmyeUnu7X2iycOrip/j4AWuqF348G9Z3ToCTsX0uhYiOdZuDQDKXbxzOpTMLKJgoaIxNHA8FKEgve3UnV0JS4VCqRwNAHDn6k1lzG1SoRdMGsTeL8sT/ToFgpxHwpcxTnC0uPtQxM80shItMPYngaimVEq+j+BjAhBetHbvV+PiX3I9LfuIDcQB6nD42UDF3IRzM8jc9ZI8SvlAvF+2LAWWvhGasrJoaoLJgMopGkviioU28stPz4hTJzGisIyirukLfm5pmkn2EX/3Z+NzXD08cOlqtZLAv00rUSIzmuX+1IVEjB78Vk6UXJg29ZYZfU5cl05nQwqxrQN8NpWQ3uOJ5Uhfaak3/wD8aDUs7OThzYRWaVa1afMYjqUVuF1QiGhq2wSVC1adnCzIBQ/v3y7G5a2YHeNCBIfbCFs+y0RyDPrH28RXgwsMzefX6ZPL7QwN4SN6AG7P9B3dvvTC2lgA9rdJQRohqGsG2tHTLd4TgOvcPgw4="
